name: CI

on:
    pull_request:
        branches:
            - 'master'
    push:
        branches:
            - 'master'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install Node
                uses: actions/setup-node@v4
                with:
                    node-version: '20.x'

            -   name: Install Rust
                uses: actions-rs/toolchain@v1
                with:
                    toolchain: stable
                    target: wasm32-unknown-unknown
                    override: true

            -   name: Install wasm-pack
                run: cargo install wasm-pack

            -   name: Build WASM module
                env:
                    RUSTFLAGS: '--cfg getrandom_backend="wasm_js"'
                run: wasm-pack build --target web --release --no-default-features --out-dir wasm

            -   name: Install dependencies
                run: npm ci
                env:
                    NODE_ENV: development

            -   name: Build
                run: npm run build

            -   name: Running tests
                run: npm run test:coverage

            -   name: Upload to Coveralls
                uses: coverallsapp/github-action@v2
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
